### ISSUE TITLE
Use class methods for your api

### ISSUE THREAD

**Issue by abinoam** [hanesbarbosa/alnum#4]
HI @hanesbarbosa,

If your api has only those 2 methods, you could use class methods instead of instance methos.
So you could bypass the "instantiation" of the object.

It would be something like:

``` ruby
Alnum::Cypher.write(32456) => "8ru"
Alnum::Cypher.read("8ru") => 32456
```

It should look like the Ruby stdlib Base64
http://ruby-doc.org/stdlib-2.1.1/libdoc/base64/rdoc/Base64.html

``` ruby
require "base64"

enc   = Base64.encode64('Send reinforcements')
                    # -> "U2VuZCByZWluZm9yY2VtZW50cw==\n"
plain = Base64.decode64(enc)
                    # -> "Send reinforcements"
```

**Comment by abinoam** [comment]
Or it could be even shorter...

``` ruby
Alnum.write(32456) => "8ru"
Alnum.read("8ru") => 32456
```

**Comment by hanesbarbosa** [comment]
Good point man! But let me explain something just to let you visualize the mindset behind the scenes.

When I planned this code I though about the classes like placeholders for future improvements, but I agree that is too much "Gold Plating" at this point. Since it's just a calculation there's no need for a instantiation, so I'm converting to a simpler module.

I'm still in love with words like "cypher" and "Decipher" (lol) so I'm gonna change this way:

``` ruby
Alnum.cypher(32456) => "8ru"
Alnum.decipher("8ru") => 32456
```
